// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kektkdjvjsagvfuvvihx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtla3RrZGp2anNhZ3ZmdXZ2aWh4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA0NzU4OTIsImV4cCI6MjA3NjA1MTg5Mn0.cWpKGxilzJs8913wrG1WN8B_f17bN21caMkqvHlGHr4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});